accessWidener	v1	named
accessible	method	net/minecraft/client/render/entity/LivingEntityRenderer	addFeature	(Lnet/minecraft/client/render/entity/feature/FeatureRenderer;)Z
accessible	field	net/minecraft/world/biome/source/BiomeSource	SPAWN_BIOMES	Ljava/util/List;
accessible	method	net/minecraft/block/entity/HopperBlockEntity	isDisabled	()Z
accessible	method	net/minecraft/block/entity/HopperBlockEntity	setCooldown	(I)V
accessible	field	net/minecraft/server/dedicated/MinecraftDedicatedServer	commandQueue	Ljava/util/List;
accessible	class	net/minecraft/recipe/TippedArrowRecipe
accessible	field	net/minecraft/loot/LootPool	bonusRollsRange	Lnet/minecraft/loot/UniformLootTableRange;
mutable	field	net/minecraft/loot/LootPool	bonusRollsRange	Lnet/minecraft/loot/UniformLootTableRange;
accessible	field	net/minecraft/loot/LootPool	rollsRange	Lnet/minecraft/loot/LootTableRange;
mutable	field	net/minecraft/loot/LootPool	rollsRange	Lnet/minecraft/loot/LootTableRange;
accessible	method	net/minecraft/client/render/model/json/ModelElement$Deserializer	<init>	()V
accessible	method	net/minecraft/world/biome/layer/BiomeLayers	stack	(JLnet/minecraft/world/biome/layer/type/ParentedLayer;Lnet/minecraft/world/biome/layer/util/LayerFactory;ILjava/util/function/LongFunction;)Lnet/minecraft/world/biome/layer/util/LayerFactory;
accessible	method	net/minecraft/client/render/entity/ItemEntityRenderer	getRenderedAmount	(Lnet/minecraft/item/ItemStack;)I
accessible	field	net/minecraft/client/render/model/ModelLoader	BLOCK_ENTITY_MARKER	Lnet/minecraft/client/render/model/json/JsonUnbakedModel;
accessible	field	net/minecraft/client/render/model/ModelLoader	GENERATION_MARKER	Lnet/minecraft/client/render/model/json/JsonUnbakedModel;
accessible	field	net/minecraft/client/render/model/ModelLoader	DEFAULT_TEXTURES	Ljava/util/Set;
accessible	field	net/minecraft/client/render/model/ModelLoader	MISSING	Lnet/minecraft/client/util/ModelIdentifier;
accessible	field	net/minecraft/client/render/model/ModelLoader	spriteAtlasData	Lnet/minecraft/client/texture/SpriteAtlasTexture$Data;
mutable	field	net/minecraft/client/render/model/ModelLoader	spriteAtlasData	Lnet/minecraft/client/texture/SpriteAtlasTexture$Data;
accessible	field	net/minecraft/client/render/model/ModelLoader	resourceManager	Lnet/minecraft/resource/ResourceManager;
accessible	field	net/minecraft/client/render/model/ModelLoader	spriteAtlas	Lnet/minecraft/client/texture/SpriteAtlasTexture;
accessible	method	net/minecraft/client/render/model/ModelLoader	loadModelFromJson	(Lnet/minecraft/util/Identifier;)Lnet/minecraft/client/render/model/json/JsonUnbakedModel;
accessible	field	net/minecraft/data/server/RecipesProvider	root	Lnet/minecraft/data/DataGenerator;
accessible	method	net/minecraft/data/server/RecipesProvider	method_10423	([Lnet/minecraft/predicate/item/ItemPredicate;)Lnet/minecraft/advancement/criterion/InventoryChangedCriterion$Conditions;
accessible	method	net/minecraft/data/server/RecipesProvider	method_10420	(Lnet/minecraft/tag/Tag;)Lnet/minecraft/advancement/criterion/InventoryChangedCriterion$Conditions;
accessible	method	net/minecraft/data/server/RecipesProvider	generate	(Ljava/util/function/Consumer;)V
accessible	method	net/minecraft/data/server/RecipesProvider	method_10427	(Lnet/minecraft/data/DataCache;Lcom/google/gson/JsonObject;Ljava/nio/file/Path;)V
accessible	method	net/minecraft/data/server/RecipesProvider	method_10426	(Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/advancement/criterion/InventoryChangedCriterion$Conditions;
accessible	method	net/minecraft/data/server/RecipesProvider	method_10422	(Lnet/minecraft/block/Block;)Lnet/minecraft/advancement/criterion/EnterBlockCriterion$Conditions;
accessible	method	net/minecraft/data/server/RecipesProvider	method_10424	(Lnet/minecraft/predicate/NumberRange$IntRange;Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/advancement/criterion/InventoryChangedCriterion$Conditions;
accessible	field	net/minecraft/client/render/model/json/Transformation$Deserializer	DEFAULT_SCALE	Lnet/minecraft/client/util/math/Vector3f;
accessible	field	net/minecraft/client/render/model/json/Transformation$Deserializer	DEFAULT_TRANSLATION	Lnet/minecraft/client/util/math/Vector3f;
accessible	field	net/minecraft/client/render/model/json/Transformation$Deserializer	DEFAULT_ROATATION	Lnet/minecraft/client/util/math/Vector3f;
accessible	method	net/minecraft/advancement/criterion/Criterions	register	(Lnet/minecraft/advancement/criterion/Criterion;)Lnet/minecraft/advancement/criterion/Criterion;
accessible	field	net/minecraft/item/Item	propertyGetters	Ljava/util/Map;
accessible	method	net/minecraft/container/ContainerType	<init>	(Lnet/minecraft/container/ContainerType$Factory;)V
accessible	field	net/minecraft/resource/NamespaceResourceManager	packList	Ljava/util/List;
accessible	method	net/minecraft/client/render/item/ItemRenderer	renderQuads	(Lnet/minecraft/client/render/BufferBuilder;Ljava/util/List;ILnet/minecraft/item/ItemStack;)V
accessible	class	net/minecraft/recipe/Ingredient$StackEntry
accessible	method	net/minecraft/recipe/Ingredient$StackEntry	<init>	(Lnet/minecraft/item/ItemStack;)V
accessible	method	net/minecraft/entity/ai/brain/MemoryModuleType	<init>	(Ljava/util/Optional;)V
accessible	method	net/minecraft/client/particle/ParticleManager	registerFactory	(Lnet/minecraft/particle/ParticleType;Lnet/minecraft/client/particle/ParticleManager$class_4091;)V
accessible	method	net/minecraft/client/particle/ParticleManager	registerFactory	(Lnet/minecraft/particle/ParticleType;Lnet/minecraft/client/particle/ParticleFactory;)V
accessible	method	net/minecraft/command/EntitySelectorOptions	putOption	(Ljava/lang/String;Lnet/minecraft/command/EntitySelectorOptions$SelectorHandler;Ljava/util/function/Predicate;Lnet/minecraft/text/Text;)V
accessible	field	net/minecraft/resource/AbstractFileResourcePack	base	Ljava/io/File;
accessible	method	net/minecraft/entity/Entity	getSavedEntityId	()Ljava/lang/String;
accessible	field	net/minecraft/server/MinecraftServer	timeReference	J
accessible	field	net/minecraft/client/render/block/entity/PistonBlockEntityRenderer	manager	Lnet/minecraft/client/render/block/BlockRenderManager;
mutable	field	net/minecraft/client/render/block/entity/PistonBlockEntityRenderer	manager	Lnet/minecraft/client/render/block/BlockRenderManager;
accessible	field	net/minecraft/world/PortalForcer	random	Ljava/util/Random;
accessible	field	net/minecraft/world/PortalForcer	world	Lnet/minecraft/server/world/ServerWorld;
accessible	field	net/minecraft/world/PortalForcer	ticketInfos	Ljava/util/Map;
accessible	method	net/minecraft/world/poi/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;ILnet/minecraft/util/SoundEvent;I)V
accessible	method	net/minecraft/world/poi/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;ILnet/minecraft/util/SoundEvent;Ljava/util/function/Predicate;I)V
accessible	method	net/minecraft/block/Block$Settings	lightLevel	(I)Lnet/minecraft/block/Block$Settings;
accessible	method	net/minecraft/block/Block$Settings	ticksRandomly	()Lnet/minecraft/block/Block$Settings;
accessible	method	net/minecraft/block/Block$Settings	sounds	(Lnet/minecraft/sound/BlockSoundGroup;)Lnet/minecraft/block/Block$Settings;
accessible	method	net/minecraft/block/Block$Settings	hasDynamicBounds	()Lnet/minecraft/block/Block$Settings;
accessible	method	net/minecraft/block/Block$Settings	dropsNothing	()Lnet/minecraft/block/Block$Settings;
accessible	method	net/minecraft/block/Block$Settings	strength	(F)Lnet/minecraft/block/Block$Settings;
accessible	field	net/minecraft/client/sound/SoundSystem	loader	Lnet/minecraft/client/sound/SoundManager;
accessible	method	net/minecraft/client/render/model/json/ModelElement	getRotatedMatrix	(Lnet/minecraft/util/math/Direction;)[F
accessible	method	net/minecraft/entity/SpawnRestriction	register	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/entity/SpawnRestriction$Location;Lnet/minecraft/world/Heightmap$Type;Lnet/minecraft/entity/SpawnRestriction$class_4306;)V
accessible	method	net/minecraft/particle/DefaultParticleType	<init>	(Z)V
accessible	field	net/minecraft/data/server/EntityLootTableGenerator	field_11344	Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
accessible	method	net/minecraft/data/server/EntityLootTableGenerator	method_16369	(Lnet/minecraft/util/Identifier;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/server/EntityLootTableGenerator	method_16368	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/item/AxeItem	<init>	(Lnet/minecraft/item/ToolMaterial;FFLnet/minecraft/item/Item$Settings;)V
accessible	field	net/minecraft/entity/mob/MobEntity	targetSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	field	net/minecraft/entity/mob/MobEntity	goalSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	class	net/minecraft/data/server/recipe/ShapedRecipeJsonFactory$ShapedRecipeJsonProvider
accessible	class	net/minecraft/world/gen/chunk/ChunkGeneratorFactory
accessible	method	net/minecraft/entity/TntEntity	explode	()V
accessible	field	net/minecraft/client/MinecraftClient	textureManager	Lnet/minecraft/client/texture/TextureManager;
accessible	method	net/minecraft/client/MinecraftClient	addBlockEntityNbt	(Lnet/minecraft/item/ItemStack;Lnet/minecraft/block/entity/BlockEntity;)Lnet/minecraft/item/ItemStack;
accessible	method	net/minecraft/client/MinecraftClient	initializeSearchableContainers	()V
accessible	field	net/minecraft/network/packet/s2c/query/QueryResponseS2CPacket	GSON	Lcom/google/gson/Gson;
accessible	field	net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher	textRenderer	Lnet/minecraft/client/font/TextRenderer;
accessible	class	net/minecraft/client/gui/screen/Screens$Provider
accessible	class	net/minecraft/client/particle/ParticleManager$class_4091
accessible	field	net/minecraft/server/network/ServerPlayerEntity	containerSyncId	I
accessible	method	net/minecraft/server/network/ServerPlayerEntity	incrementContainerSyncId	()V
accessible	field	net/minecraft/client/gui/hud/InGameHud	titleTotalTicks	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	field_2013	F
accessible	field	net/minecraft/client/gui/hud/InGameHud	playerListHud	Lnet/minecraft/client/gui/hud/PlayerListHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	field_2014	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	chatHud	Lnet/minecraft/client/gui/hud/ChatHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	random	Ljava/util/Random;
accessible	field	net/minecraft/client/gui/hud/InGameHud	title	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/hud/InGameHud	titleRemainTicks	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	titleFadeOutTicks	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	ticks	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	listeners	Ljava/util/Map;
accessible	field	net/minecraft/client/gui/hud/InGameHud	field_2012	J
accessible	field	net/minecraft/client/gui/hud/InGameHud	scaledWidth	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	field_2032	J
accessible	field	net/minecraft/client/gui/hud/InGameHud	overlayMessage	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/hud/InGameHud	spectatorHud	Lnet/minecraft/client/gui/hud/SpectatorHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	itemRenderer	Lnet/minecraft/client/render/item/ItemRenderer;
accessible	field	net/minecraft/client/gui/hud/InGameHud	subtitle	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/hud/InGameHud	field_2033	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	PUMPKIN_BLUR	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/client/gui/hud/InGameHud	overlayTinted	Z
accessible	field	net/minecraft/client/gui/hud/InGameHud	VIGNETTE_TEX	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/client/gui/hud/InGameHud	bossBarHud	Lnet/minecraft/client/gui/hud/BossBarHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	overlayRemaining	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	titleFadeInTicks	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	WIDGETS_TEX	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/client/gui/hud/InGameHud	scaledHeight	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	heldItemTooltipFade	I
accessible	field	net/minecraft/client/gui/hud/InGameHud	subtitlesHud	Lnet/minecraft/client/gui/hud/SubtitlesHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	client	Lnet/minecraft/client/MinecraftClient;
accessible	field	net/minecraft/client/gui/hud/InGameHud	debugHud	Lnet/minecraft/client/gui/hud/DebugHud;
accessible	field	net/minecraft/client/gui/hud/InGameHud	currentStack	Lnet/minecraft/item/ItemStack;
accessible	method	net/minecraft/client/gui/hud/InGameHud	renderVignetteOverlay	(Lnet/minecraft/entity/Entity;)V
accessible	method	net/minecraft/client/gui/hud/InGameHud	renderCrosshair	()V
accessible	method	net/minecraft/client/gui/hud/InGameHud	renderPortalOverlay	(F)V
accessible	method	net/minecraft/client/gui/hud/InGameHud	renderScoreboardSidebar	(Lnet/minecraft/scoreboard/ScoreboardObjective;)V
accessible	method	net/minecraft/client/gui/hud/InGameHud	renderPumpkinOverlay	()V
accessible	method	net/minecraft/client/render/model/json/ModelElementTexture$Deserializer	<init>	()V
accessible	method	net/minecraft/entity/mob/AbstractSkeletonEntity	getStepSound	()Lnet/minecraft/sound/SoundEvent;
accessible	method	net/minecraft/world/chunk/ChunkStatus	<init>	(Ljava/lang/String;Lnet/minecraft/world/chunk/ChunkStatus;ILjava/util/EnumSet;Lnet/minecraft/world/chunk/ChunkStatus$ChunkType;Lnet/minecraft/world/chunk/ChunkStatus$Task;Lnet/minecraft/world/chunk/ChunkStatus$class_4305;)V
accessible	method	net/minecraft/world/biome/Biome	computeTemperature	(Lnet/minecraft/util/math/BlockPos;)F
accessible	method	net/minecraft/entity/mob/WitherSkeletonEntity	l	()Lnet/minecraft/sound/SoundEvent;
accessible	field	net/minecraft/client/render/entity/EntityRenderDispatcher	renderers	Ljava/util/Map;
accessible	method	net/minecraft/client/render/entity/EntityRenderDispatcher	register	(Ljava/lang/Class;Lnet/minecraft/client/render/entity/EntityRenderer;)V
accessible	field	net/minecraft/server/world/ServerChunkManager	chunkGenerator	Lnet/minecraft/world/gen/chunk/ChunkGenerator;
accessible	field	net/minecraft/server/world/ServerChunkManager	world	Lnet/minecraft/server/world/ServerWorld;
accessible	method	net/minecraft/entity/damage/DamageSource	thorns	(Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	mob	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	isOutOfWorld	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	getDeathMessage	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/text/Text;
accessible	method	net/minecraft/entity/damage/DamageSource	setFire	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	isScaledWithDifficulty	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	getName	()Ljava/lang/String;
accessible	method	net/minecraft/entity/damage/DamageSource	method_5510	()Lnet/minecraft/util/math/Vec3d;
accessible	method	net/minecraft/entity/damage/DamageSource	setUsesMagic	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	thrownProjectile	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	explosion	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	isFire	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	isUnblockable	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	setProjectile	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	netherBed	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	bypassesArmor	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	<init>	(Ljava/lang/String;)V
accessible	method	net/minecraft/entity/damage/DamageSource	explosion	(Lnet/minecraft/world/explosion/Explosion;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	getSource	()Lnet/minecraft/entity/Entity;
accessible	method	net/minecraft/entity/damage/DamageSource	setUnblockable	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	isProjectile	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	setBypassesArmor	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	getExhaustion	()F
accessible	method	net/minecraft/entity/damage/DamageSource	explosiveProjectile	(Lnet/minecraft/entity/projectile/ExplosiveProjectileEntity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	player	(Lnet/minecraft/entity/player/PlayerEntity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	setExplosive	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	magic	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	setOutOfWorld	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	getMagic	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	getAttacker	()Lnet/minecraft/entity/Entity;
accessible	method	net/minecraft/entity/damage/DamageSource	isExplosive	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	setScaledWithDifficulty	()Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	trident	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	arrow	(Lnet/minecraft/entity/projectile/ProjectileEntity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/entity/damage/DamageSource	isSourceCreativePlayer	()Z
accessible	method	net/minecraft/entity/damage/DamageSource	mobProjectile	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/entity/damage/DamageSource;
accessible	method	net/minecraft/block/Block	dropExperience	(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;I)V
accessible	field	net/minecraft/server/world/ChunkHolder	blockUpdatePositions	[S
mutable	field	net/minecraft/server/world/ChunkHolder	blockUpdatePositions	[S
accessible	field	net/minecraft/client/render/model/json/JsonUnbakedModel	ambientOcclusion	Z
accessible	field	net/minecraft/client/render/model/json/JsonUnbakedModel	parent	Lnet/minecraft/client/render/model/json/JsonUnbakedModel;
accessible	field	net/minecraft/client/render/model/json/JsonUnbakedModel	textureMap	Ljava/util/Map;
accessible	method	net/minecraft/client/render/model/json/JsonUnbakedModel	getOverrides	()Ljava/util/List;
accessible	method	net/minecraft/client/render/model/json/ModelTransformation$Deserializer	<init>	()V
accessible	method	net/minecraft/entity/mob/SkeletonEntity	l	()Lnet/minecraft/sound/SoundEvent;
accessible	method	net/minecraft/village/VillagerProfession	<init>	(Ljava/lang/String;Lnet/minecraft/world/poi/PointOfInterestType;Lcom/google/common/collect/ImmutableSet;Lcom/google/common/collect/ImmutableSet;)V
accessible	method	net/minecraft/world/biome/DeepFrozenOceanBiome	c	(Lnet/minecraft/util/math/BlockPos;)F
accessible	method	net/minecraft/client/texture/Sprite	getFramePixel	(IIII)I
accessible	field	net/minecraft/client/gui/hud/DebugHud	blockHit	Lnet/minecraft/util/hit/HitResult;
accessible	field	net/minecraft/client/gui/hud/DebugHud	fluidHit	Lnet/minecraft/util/hit/HitResult;
accessible	field	net/minecraft/entity/ExperienceOrbEntity	amount	I
accessible	class	net/minecraft/tag/BlockTags$CachingTag
accessible	method	net/minecraft/client/render/model/json/ModelItemOverride$Deserializer	<init>	()V
accessible	method	net/minecraft/command/EntitySelectorReader	buildPredicate	()V
accessible	method	net/minecraft/command/EntitySelectorReader	readArguments	()V
accessible	method	net/minecraft/particle/ParticleType	<init>	(ZLnet/minecraft/particle/ParticleEffect$Factory;)V
accessible	method	net/minecraft/client/render/model/json/ModelElementFace$Deserializer	<init>	()V
accessible	field	net/minecraft/entity/player/PlayerEntity	spawnPosition	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/entity/player/PlayerEntity	spawnForced	Z
accessible	method	net/minecraft/entity/player/PlayerEntity	closeContainer	()V
accessible	field	net/minecraft/world/level/LevelGeneratorType	TYPES	[Lnet/minecraft/world/level/LevelGeneratorType;
mutable	field	net/minecraft/world/level/LevelGeneratorType	TYPES	[Lnet/minecraft/world/level/LevelGeneratorType;
accessible	method	net/minecraft/entity/ai/brain/Activity	<init>	(Ljava/lang/String;)V
accessible	method	net/minecraft/client/render/model/json/ModelItemPropertyOverrideList	<init>	()V
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10371	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10381	(Lnet/minecraft/block/Block;Lnet/minecraft/world/loot/condition/LootCondition$Builder;Lnet/minecraft/loot/entry/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10383	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_16293	(Lnet/minecraft/block/Block;Ljava/util/function/Function;)V
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10377	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10387	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10373	(Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10397	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/entry/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10385	(Lnet/minecraft/block/Block;Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10380	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/entry/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10392	(Lnet/minecraft/item/ItemConvertible;Lnet/minecraft/loot/condition/LootConditionConsumingBuilder;)Ljava/lang/Object;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10378	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10389	(Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_16876	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10391	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;Lnet/minecraft/item/Item;Lnet/minecraft/world/loot/condition/LootCondition$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10396	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10390	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10388	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/entry/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_16258	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10372	(Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10394	(Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10382	(Lnet/minecraft/block/Block;Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10375	(Lnet/minecraft/block/Block;Lnet/minecraft/state/property/Property;Ljava/lang/Comparable;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10386	(Lnet/minecraft/block/Block;Lnet/minecraft/item/ItemConvertible;Lnet/minecraft/loot/LootTableRange;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10384	(Lnet/minecraft/item/ItemConvertible;Lnet/minecraft/loot/LootTableRange;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_10393	(Lnet/minecraft/item/ItemConvertible;Lnet/minecraft/loot/function/LootFunctionConsumingBuilder;)Ljava/lang/Object;
accessible	method	net/minecraft/data/server/BlockLootTableGenerator	method_16877	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	class	net/minecraft/container/ContainerType$Factory
accessible	method	net/minecraft/world/biome/FrozenOceanBiome	c	(Lnet/minecraft/util/math/BlockPos;)F
accessible	method	net/minecraft/client/gui/screen/Screens	register	(Lnet/minecraft/container/ContainerType;Lnet/minecraft/client/gui/screen/Screens$Provider;)V
accessible	field	net/minecraft/container/AnvilContainer	field_7776	I
accessible	method	net/minecraft/fluid/Fluid	getRenderLayer	()Lnet/minecraft/client/render/RenderLayer;
accessible	class	net/minecraft/recipe/Ingredient$Entry
accessible	class	net/minecraft/recipe/Ingredient
extendable	class	net/minecraft/recipe/Ingredient
accessible	method	net/minecraft/recipe/Ingredient	write	(Lnet/minecraft/util/PacketByteBuf;)V
extendable	method	net/minecraft/recipe/Ingredient	write	(Lnet/minecraft/util/PacketByteBuf;)V
accessible	method	net/minecraft/recipe/Ingredient	ofEntries	(Ljava/util/stream/Stream;)Lnet/minecraft/recipe/Ingredient;
accessible	method	net/minecraft/recipe/Ingredient	<init>	(Ljava/util/stream/Stream;)V
accessible	method	net/minecraft/client/render/GameRenderer	loadShader	(Lnet/minecraft/util/Identifier;)V
accessible	field	net/minecraft/item/ItemGroup	GROUPS	[Lnet/minecraft/item/ItemGroup;
mutable	field	net/minecraft/item/ItemGroup	GROUPS	[Lnet/minecraft/item/ItemGroup;
accessible	field	net/minecraft/world/World	rainGradientPrev	F
accessible	field	net/minecraft/world/World	thunderGradientPrev	F
accessible	field	net/minecraft/world/World	rainGradient	F
accessible	field	net/minecraft/world/World	thunderGradient	F
accessible	method	net/minecraft/world/World	isHeightInvalid	(Lnet/minecraft/util/math/BlockPos;)Z
accessible	method	net/minecraft/world/World	isValid	(Lnet/minecraft/util/math/BlockPos;)Z
accessible	method	net/minecraft/entity/mob/StrayEntity	l	()Lnet/minecraft/sound/SoundEvent;
accessible	field	net/minecraft/client/render/item/ItemModels	modelIds	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	method	net/minecraft/client/render/BufferBuilder	setColor	(IIII)V
accessible	method	net/minecraft/client/render/BufferBuilder	getColorIndex	(I)I
accessible	field	net/minecraft/util/IdList	nextId	I
accessible	field	net/minecraft/util/IdList	idMap	Ljava/util/IdentityHashMap;
accessible	field	net/minecraft/util/IdList	list	Ljava/util/List;
accessible	field	net/minecraft/client/gui/widget/EntryListWidget$Entry	list	Lnet/minecraft/client/gui/widget/EntryListWidget;
accessible	method	net/minecraft/item/PickaxeItem	<init>	(Lnet/minecraft/item/ToolMaterial;IFLnet/minecraft/item/Item$Settings;)V
accessible	class	net/minecraft/nbt/AbstractNumberTag
accessible	method	net/minecraft/world/GameRules	register	(Ljava/lang/String;Lnet/minecraft/world/GameRules$RuleType;)Lnet/minecraft/world/GameRules$RuleKey;
accessible	field	net/minecraft/util/WeightedPicker$Entry	weight	I
accessible	method	net/minecraft/entity/ai/brain/sensor/SensorType	<init>	(Ljava/util/function/Supplier;)V
accessible	class	net/minecraft/recipe/Ingredient$TagEntry
accessible	method	net/minecraft/recipe/Ingredient$TagEntry	<init>	(Lnet/minecraft/tags/Tag;)V
accessible	method	net/minecraft/util/thread/ThreadExecutor	submitAsync	(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;
