accessWidener	v1	named
accessible	field	net/minecraft/client/renderer/ItemModelMesher	modelLocations	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	method	net/minecraft/block/ChorusPlantBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/EndRodBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SkullWallPlayerBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/entity/Entity	getEntityString	()Ljava/lang/String;
accessible	method	net/minecraft/tags/FluidTags	makeWrapperTag	(Ljava/lang/String;)Lnet/minecraft/tags/ITag$INamedTag;
accessible	method	net/minecraft/tags/EntityTypeTags	getTagById	(Ljava/lang/String;)Lnet/minecraft/tags/ITag$INamedTag;
accessible	method	net/minecraft/entity/ai/brain/schedule/Activity	<init>	(Ljava/lang/String;)V
accessible	method	net/minecraft/block/SugarCaneBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/util/WeightedRandom$Item	itemWeight	I
accessible	method	net/minecraft/command/arguments/EntitySelectorParser	updateFilter	()V
accessible	method	net/minecraft/command/arguments/EntitySelectorParser	parseArguments	()V
accessible	class	net/minecraft/world/biome/Biome$Climate
accessible	field	net/minecraft/world/biome/Biome$Climate	temperatureModifier	Lnet/minecraft/world/biome/Biome$TemperatureModifier;
accessible	field	net/minecraft/world/biome/Biome$Climate	temperature	F
accessible	field	net/minecraft/world/biome/Biome$Climate	downfall	F
accessible	field	net/minecraft/world/biome/Biome$Climate	precipitation	Lnet/minecraft/world/biome/Biome$RainType;
accessible	method	net/minecraft/world/biome/Biome$Climate	<init>	(Lnet/minecraft/world/biome/Biome$RainType;FLnet/minecraft/world/biome/Biome$TemperatureModifier;F)V
accessible	method	net/minecraft/data/loot/BlockLootTables	onlyWithSilkTouch	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingItemWithFortune	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingByAge	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingSlab	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithSilkTouchOrRandomly	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;Lnet/minecraft/loot/IRandomRange;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithChancesAndSticks	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	registerLootTable	(Lnet/minecraft/block/Block;Ljava/util/function/Function;)V
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingSeeds	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	dropping	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingAndBonusWhen	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;Lnet/minecraft/item/Item;Lnet/minecraft/loot/conditions/ILootCondition$IBuilder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingAndFlowerPot	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingItemRarely	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	withSurvivesExplosion	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/loot/ILootConditionConsumer;)Ljava/lang/Object;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithSilkTouch	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithSilkTouch	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithPatterns	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	withExplosionDecay	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/loot/ILootFunctionConsumer;)Ljava/lang/Object;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithName	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingRandomly	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/loot/IRandomRange;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWhen	(Lnet/minecraft/block/Block;Lnet/minecraft/state/Property;Ljava/lang/Comparable;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithChancesSticksAndApples	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	onlyWithShears	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	registerLootTable	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithSilkTouchOrShears	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	dropping	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/conditions/ILootCondition$IBuilder;Lnet/minecraft/loot/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithShears	(Lnet/minecraft/block/Block;Lnet/minecraft/loot/LootEntry$Builder;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	droppingWithContents	(Lnet/minecraft/block/Block;)Lnet/minecraft/loot/LootTable$Builder;
accessible	method	net/minecraft/block/TallGrassBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/Minecraft	textureManager	Lnet/minecraft/client/renderer/texture/TextureManager;
accessible	method	net/minecraft/client/Minecraft	populateSearchTreeManager	()V
accessible	method	net/minecraft/client/Minecraft	storeTEInStack	(Lnet/minecraft/item/ItemStack;Lnet/minecraft/tileentity/TileEntity;)Lnet/minecraft/item/ItemStack;
accessible	method	net/minecraft/block/DeadCoralWallFanBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/inventory/container/ContainerType	<init>	(Lnet/minecraft/inventory/container/ContainerType$IFactory;)V
accessible	method	net/minecraft/client/renderer/GameRenderer	loadShader	(Lnet/minecraft/util/ResourceLocation;)V
accessible	method	net/minecraft/block/AirBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/CoralFanBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/JukeboxBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/FlowingFluidBlock	<init>	(Lnet/minecraft/fluid/FlowingFluid;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	class	net/minecraft/item/crafting/Ingredient$SingleItemList
accessible	method	net/minecraft/item/crafting/Ingredient$SingleItemList	<init>	(Lnet/minecraft/item/ItemStack;)V
accessible	method	net/minecraft/entity/monster/WitherSkeletonEntity	getStepSound	()Lnet/minecraft/util/SoundEvent;
accessible	method	net/minecraft/block/GrassPathBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/PoweredRailBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/settings/KeyBinding	pressed	Z
accessible	method	net/minecraft/block/Block	dropXpOnBlockBreak	(Lnet/minecraft/world/server/ServerWorld;Lnet/minecraft/util/math/BlockPos;I)V
accessible	field	net/minecraft/world/biome/MobSpawnInfo$Builder	validSpawnBiomeForPlayer	Z
accessible	field	net/minecraft/world/biome/MobSpawnInfo$Builder	spawners	Ljava/util/Map;
accessible	field	net/minecraft/world/biome/MobSpawnInfo$Builder	spawnCosts	Ljava/util/Map;
accessible	field	net/minecraft/world/biome/MobSpawnInfo$Builder	creatureSpawnProbability	F
accessible	method	net/minecraft/block/SeaPickleBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/CactusBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/item/ToolItem	<init>	(FFLnet/minecraft/item/IItemTier;Ljava/util/Set;Lnet/minecraft/item/Item$Properties;)V
accessible	field	net/minecraft/client/renderer/entity/EntityRendererManager	renderers	Ljava/util/Map;
accessible	method	net/minecraft/client/renderer/entity/EntityRendererManager	register	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/client/renderer/entity/EntityRenderer;)V
accessible	method	net/minecraft/block/BlastFurnaceBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/CartographyTableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SaplingBlock	<init>	(Lnet/minecraft/block/trees/Tree;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/EnderChestBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/WetSpongeBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SmithingTableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SeaGrassBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/world/gen/blockstateprovider/BlockStateProviderType	<init>	(Lcom/mojang/serialization/Codec;)V
accessible	class	net/minecraft/data/ShapedRecipeBuilder$Result
accessible	method	net/minecraft/block/SnowyDirtBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/item/ItemModelsProperties	registerProperty	(Lnet/minecraft/item/Item;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/item/IItemPropertyGetter;)V
accessible	method	net/minecraft/block/AttachedStemBlock	<init>	(Lnet/minecraft/block/StemGrownBlock;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/util/concurrent/ThreadTaskExecutor	deferTask	(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;
accessible	field	net/minecraft/data/TagsProvider	tagToBuilder	Ljava/util/Map;
accessible	method	net/minecraft/block/StairsBlock	<init>	(Lnet/minecraft/block/BlockState;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/TrapDoorBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/entity/merchant/villager/VillagerProfession	<init>	(Ljava/lang/String;Lnet/minecraft/village/PointOfInterestType;Lcom/google/common/collect/ImmutableSet;Lcom/google/common/collect/ImmutableSet;Lnet/minecraft/util/SoundEvent;)V
accessible	method	net/minecraft/client/renderer/model/BlockPart	getFaceUvs	(Lnet/minecraft/util/Direction;)[F
accessible	method	net/minecraft/block/CarpetBlock	<init>	(Lnet/minecraft/item/DyeColor;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/advancements/CriteriaTriggers	register	(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger;
accessible	method	net/minecraft/block/SpawnerBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/world/gen/treedecorator/TreeDecoratorType	<init>	(Lcom/mojang/serialization/Codec;)V
accessible	method	net/minecraft/util/DamageSource	setDamageIsAbsolute	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	setDamageBypassesArmor	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	<init>	(Ljava/lang/String;)V
accessible	method	net/minecraft/util/DamageSource	setFireDamage	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	setDamageAllowedInCreativeMode	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/block/SkullPlayerBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/StructureBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/inventory/container/RepairContainer	materialCost	I
accessible	method	net/minecraft/world/gen/foliageplacer/FoliagePlacerType	<init>	(Lcom/mojang/serialization/Codec;)V
accessible	class	net/minecraft/item/crafting/Ingredient
extendable	class	net/minecraft/item/crafting/Ingredient
accessible	method	net/minecraft/item/crafting/Ingredient	<init>	(Ljava/util/stream/Stream;)V
accessible	method	net/minecraft/item/crafting/Ingredient	write	(Lnet/minecraft/network/PacketBuffer;)V
extendable	method	net/minecraft/item/crafting/Ingredient	write	(Lnet/minecraft/network/PacketBuffer;)V
accessible	method	net/minecraft/item/crafting/Ingredient	deserializeItemList	(Lcom/google/gson/JsonObject;)Lnet/minecraft/item/crafting/Ingredient$IItemList;
accessible	method	net/minecraft/item/crafting/Ingredient	fromItemListStream	(Ljava/util/stream/Stream;)Lnet/minecraft/item/crafting/Ingredient;
accessible	method	net/minecraft/block/CakeBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/LeverBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/renderer/model/BlockModel	parent	Lnet/minecraft/client/renderer/model/BlockModel;
accessible	field	net/minecraft/client/renderer/model/BlockModel	ambientOcclusion	Z
accessible	field	net/minecraft/client/renderer/model/BlockModel	textures	Ljava/util/Map;
accessible	method	net/minecraft/block/RedstoneWallTorchBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/village/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;II)V
accessible	method	net/minecraft/village/PointOfInterestType	getAllStates	(Lnet/minecraft/block/Block;)Ljava/util/Set;
accessible	method	net/minecraft/village/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;ILjava/util/function/Predicate;I)V
accessible	field	net/minecraft/client/audio/SoundEngine	sndHandler	Lnet/minecraft/client/audio/SoundHandler;
accessible	method	net/minecraft/block/StemBlock	<init>	(Lnet/minecraft/block/StemGrownBlock;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SkullBlock	<init>	(Lnet/minecraft/block/SkullBlock$ISkullType;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/WitherSkeletonWallSkullBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/TorchBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;Lnet/minecraft/particles/IParticleData;)V
accessible	method	net/minecraft/block/FletchingTableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/tags/ItemTags	makeWrapperTag	(Ljava/lang/String;)Lnet/minecraft/tags/ITag$INamedTag;
accessible	class	net/minecraft/client/particle/ParticleManager$IParticleMetaFactory
accessible	method	net/minecraft/world/storage/FolderName	<init>	(Ljava/lang/String;)V
accessible	field	net/minecraft/tags/TagRegistry$NamedTag	tag	Lnet/minecraft/tags/ITag;
accessible	method	net/minecraft/block/BushBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/EnchantingTableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/entity/item/ExperienceOrbEntity	xpValue	I
accessible	method	net/minecraft/item/MusicDiscItem	<init>	(ILnet/minecraft/util/SoundEvent;Lnet/minecraft/item/Item$Properties;)V
accessible	method	net/minecraft/client/renderer/model/ItemCameraTransforms$Deserializer	<init>	()V
accessible	class	net/minecraft/item/crafting/Ingredient$TagList
accessible	method	net/minecraft/item/crafting/Ingredient$TagList	<init>	(Lnet/minecraft/tags/ITag;)V
accessible	field	net/minecraft/server/dedicated/DedicatedServer	pendingCommandList	Ljava/util/List;
accessible	method	net/minecraft/particles/ParticleType	<init>	(ZLnet/minecraft/particles/IParticleData$IDeserializer;)V
accessible	method	net/minecraft/client/renderer/model/BlockFaceUV$Deserializer	<init>	()V
accessible	method	net/minecraft/item/HoeItem	<init>	(Lnet/minecraft/item/IItemTier;IFLnet/minecraft/item/Item$Properties;)V
accessible	method	net/minecraft/client/renderer/ItemRenderer	renderModel	(Lnet/minecraft/client/renderer/model/IBakedModel;Lnet/minecraft/item/ItemStack;IILcom/mojang/blaze3d/matrix/MatrixStack;Lcom/mojang/blaze3d/vertex/IVertexBuilder;)V
accessible	method	net/minecraft/client/renderer/ItemRenderer	renderQuads	(Lcom/mojang/blaze3d/matrix/MatrixStack;Lcom/mojang/blaze3d/vertex/IVertexBuilder;Ljava/util/List;Lnet/minecraft/item/ItemStack;II)V
accessible	method	net/minecraft/block/EndPortalBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/world/World	rainingStrength	F
accessible	field	net/minecraft/world/World	prevRainingStrength	F
accessible	field	net/minecraft/world/World	prevThunderingStrength	F
accessible	field	net/minecraft/world/World	thunderingStrength	F
accessible	field	net/minecraft/resources/ResourcePack	file	Ljava/io/File;
accessible	method	net/minecraft/block/WallTorchBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;Lnet/minecraft/particles/IParticleData;)V
accessible	method	net/minecraft/block/PumpkinBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/particles/BasicParticleType	<init>	(Z)V
accessible	field	net/minecraft/network/status/server/SServerInfoPacket	GSON	Lcom/google/gson/Gson;
accessible	method	net/minecraft/client/renderer/model/ItemOverride$Deserializer	<init>	()V
accessible	method	net/minecraft/entity/ai/brain/sensor/SensorType	<init>	(Ljava/util/function/Supplier;)V
accessible	method	net/minecraft/block/ChestBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;Ljava/util/function/Supplier;)V
accessible	field	net/minecraft/client/GameSettings	keyBindings	[Lnet/minecraft/client/settings/KeyBinding;
mutable	field	net/minecraft/client/GameSettings	keyBindings	[Lnet/minecraft/client/settings/KeyBinding;
accessible	field	net/minecraft/tags/NetworkTagManager	blocks	Lnet/minecraft/tags/TagCollectionReader;
mutable	field	net/minecraft/tags/NetworkTagManager	blocks	Lnet/minecraft/tags/TagCollectionReader;
accessible	field	net/minecraft/tags/NetworkTagManager	fluids	Lnet/minecraft/tags/TagCollectionReader;
mutable	field	net/minecraft/tags/NetworkTagManager	fluids	Lnet/minecraft/tags/TagCollectionReader;
accessible	field	net/minecraft/tags/NetworkTagManager	entityTypes	Lnet/minecraft/tags/TagCollectionReader;
mutable	field	net/minecraft/tags/NetworkTagManager	entityTypes	Lnet/minecraft/tags/TagCollectionReader;
accessible	field	net/minecraft/tags/NetworkTagManager	items	Lnet/minecraft/tags/TagCollectionReader;
mutable	field	net/minecraft/tags/NetworkTagManager	items	Lnet/minecraft/tags/TagCollectionReader;
accessible	method	net/minecraft/client/renderer/model/BlockPartFace$Deserializer	<init>	()V
accessible	field	net/minecraft/client/gui/widget/list/AbstractList$AbstractListEntry	list	Lnet/minecraft/client/gui/widget/list/AbstractList;
accessible	method	net/minecraft/client/particle/ParticleManager	registerFactory	(Lnet/minecraft/particles/ParticleType;Lnet/minecraft/client/particle/IParticleFactory;)V
accessible	method	net/minecraft/client/particle/ParticleManager	registerFactory	(Lnet/minecraft/particles/ParticleType;Lnet/minecraft/client/particle/ParticleManager$IParticleMetaFactory;)V
accessible	method	net/minecraft/block/FourWayBlock	<init>	(FFFFFLnet/minecraft/block/AbstractBlock$Properties;)V
accessible	class	net/minecraft/item/crafting/Ingredient$IItemList
accessible	field	net/minecraft/data/RecipeProvider	generator	Lnet/minecraft/data/DataGenerator;
accessible	method	net/minecraft/data/RecipeProvider	saveRecipeAdvancement	(Lnet/minecraft/data/DirectoryCache;Lcom/google/gson/JsonObject;Ljava/nio/file/Path;)V
accessible	method	net/minecraft/data/RecipeProvider	registerRecipes	(Ljava/util/function/Consumer;)V
accessible	method	net/minecraft/data/RecipeProvider	hasItem	(Lnet/minecraft/tags/ITag;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	hasItem	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	enteredBlock	(Lnet/minecraft/block/Block;)Lnet/minecraft/advancements/criterion/EnterBlockTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	hasItem	([Lnet/minecraft/advancements/criterion/ItemPredicate;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/block/KelpBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/item/AxeItem	<init>	(Lnet/minecraft/item/IItemTier;FFLnet/minecraft/item/Item$Properties;)V
accessible	field	net/minecraft/client/renderer/model/ModelBakery	LOCATIONS_BUILTIN_TEXTURES	Ljava/util/Set;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	sheetData	Ljava/util/Map;
mutable	field	net/minecraft/client/renderer/model/ModelBakery	sheetData	Ljava/util/Map;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	resourceManager	Lnet/minecraft/resources/IResourceManager;
accessible	method	net/minecraft/client/renderer/model/ModelBakery	loadModel	(Lnet/minecraft/util/ResourceLocation;)Lnet/minecraft/client/renderer/model/BlockModel;
accessible	method	net/minecraft/block/AbstractCoralPlantBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/EndGatewayBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/client/renderer/model/BlockPart$Deserializer	<init>	()V
accessible	field	net/minecraft/entity/MobEntity	goalSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	field	net/minecraft/entity/MobEntity	targetSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	method	net/minecraft/entity/ai/brain/memory/MemoryModuleType	<init>	(Ljava/util/Optional;)V
accessible	method	net/minecraft/client/gui/screen/WorldOptionsScreen	func_239043_a_	(Lnet/minecraft/world/gen/settings/DimensionGeneratorSettings;)V
accessible	method	net/minecraft/block/RedstoneTorchBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/LecternBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/gui/IngameGui	rand	Ljava/util/Random;
accessible	field	net/minecraft/client/gui/IngameGui	persistantChatGUI	Lnet/minecraft/client/gui/NewChatGui;
accessible	field	net/minecraft/client/gui/IngameGui	itemRenderer	Lnet/minecraft/client/renderer/ItemRenderer;
accessible	field	net/minecraft/client/gui/IngameGui	VIGNETTE_TEX_PATH	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	PUMPKIN_BLUR_TEX_PATH	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	field_243249_e	Lnet/minecraft/util/text/ITextComponent;
accessible	field	net/minecraft/client/gui/IngameGui	titleFadeIn	I
accessible	field	net/minecraft/client/gui/IngameGui	titleDisplayTime	I
accessible	field	net/minecraft/client/gui/IngameGui	titleFadeOut	I
accessible	field	net/minecraft/client/gui/IngameGui	lastSystemTime	J
accessible	field	net/minecraft/client/gui/IngameGui	playerHealth	I
accessible	field	net/minecraft/client/gui/IngameGui	healthUpdateCounter	J
accessible	field	net/minecraft/client/gui/IngameGui	overlayMessage	Lnet/minecraft/util/text/ITextComponent;
accessible	field	net/minecraft/client/gui/IngameGui	mc	Lnet/minecraft/client/Minecraft;
accessible	field	net/minecraft/client/gui/IngameGui	ticks	I
accessible	field	net/minecraft/client/gui/IngameGui	chatListeners	Ljava/util/Map;
accessible	field	net/minecraft/client/gui/IngameGui	remainingHighlightTicks	I
accessible	field	net/minecraft/client/gui/IngameGui	highlightingItemStack	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/client/gui/IngameGui	overlayBoss	Lnet/minecraft/client/gui/overlay/BossOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	overlayDebug	Lnet/minecraft/client/gui/overlay/DebugOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	spectatorGui	Lnet/minecraft/client/gui/SpectatorGui;
accessible	field	net/minecraft/client/gui/IngameGui	overlayPlayerList	Lnet/minecraft/client/gui/overlay/PlayerTabOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	titlesTimer	I
accessible	field	net/minecraft/client/gui/IngameGui	overlaySubtitle	Lnet/minecraft/client/gui/overlay/SubtitleOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	scaledWidth	I
accessible	field	net/minecraft/client/gui/IngameGui	scaledHeight	I
accessible	field	net/minecraft/client/gui/IngameGui	WIDGETS_TEX_PATH	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	displayedTitle	Lnet/minecraft/util/text/ITextComponent;
accessible	field	net/minecraft/client/gui/IngameGui	displayedSubTitle	Lnet/minecraft/util/text/ITextComponent;
accessible	field	net/minecraft/client/gui/IngameGui	animateOverlayMessageColor	Z
accessible	field	net/minecraft/client/gui/IngameGui	lastPlayerHealth	I
accessible	field	net/minecraft/client/gui/IngameGui	overlayMessageTime	I
accessible	method	net/minecraft/client/gui/IngameGui	renderVignette	(Lnet/minecraft/entity/Entity;)V
accessible	method	net/minecraft/client/gui/IngameGui	func_238448_a_	(Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/gui/FontRenderer;III)V
accessible	method	net/minecraft/client/gui/IngameGui	func_238456_d_	(Lcom/mojang/blaze3d/matrix/MatrixStack;)V
accessible	method	net/minecraft/client/gui/IngameGui	func_238447_a_	(Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/scoreboard/ScoreObjective;)V
accessible	method	net/minecraft/client/gui/IngameGui	renderPumpkinOverlay	()V
accessible	method	net/minecraft/client/gui/IngameGui	renderPortal	(F)V
accessible	method	net/minecraft/block/NyliumBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/world/chunk/ChunkStatus	<init>	(Ljava/lang/String;Lnet/minecraft/world/chunk/ChunkStatus;ILjava/util/EnumSet;Lnet/minecraft/world/chunk/ChunkStatus$Type;Lnet/minecraft/world/chunk/ChunkStatus$IGenerationWorker;Lnet/minecraft/world/chunk/ChunkStatus$ILoadingWorker;)V
accessible	method	net/minecraft/block/NetherWartBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	TRANSLATION_DEFAULT	Lnet/minecraft/util/math/vector/Vector3f;
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	ROTATION_DEFAULT	Lnet/minecraft/util/math/vector/Vector3f;
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	SCALE_DEFAULT	Lnet/minecraft/util/math/vector/Vector3f;
accessible	method	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	<init>	()V
accessible	method	net/minecraft/block/CoralFinBlock	<init>	(Lnet/minecraft/block/Block;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/WoodButtonBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/WallSkullBlock	<init>	(Lnet/minecraft/block/SkullBlock$ISkullType;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/CraftingTableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/data/loot/EntityLootTables	ON_FIRE	Lnet/minecraft/advancements/criterion/EntityPredicate$Builder;
accessible	method	net/minecraft/data/loot/EntityLootTables	registerLootTable	(Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/loot/EntityLootTables	registerLootTable	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/loot/LootTable$Builder;)V
accessible	method	net/minecraft/block/RepeaterBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/world/Teleporter	world	Lnet/minecraft/world/server/ServerWorld;
accessible	method	net/minecraft/block/SmokerBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	class	net/minecraft/client/gui/ScreenManager$IScreenFactory
accessible	method	net/minecraft/block/WeightedPressurePlateBlock	<init>	(ILnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/ScaffoldingBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/CoralPlantBlock	<init>	(Lnet/minecraft/block/Block;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/item/ItemGroup	GROUPS	[Lnet/minecraft/item/ItemGroup;
mutable	field	net/minecraft/item/ItemGroup	GROUPS	[Lnet/minecraft/item/ItemGroup;
accessible	method	net/minecraft/block/StructureVoidBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/DeadBushBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/DeadCoralPlantBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/MelonBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SnowBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/FurnaceBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/world/gen/layer/LayerUtil	repeat	(JLnet/minecraft/world/gen/layer/traits/IAreaTransformer1;Lnet/minecraft/world/gen/area/IAreaFactory;ILjava/util/function/LongFunction;)Lnet/minecraft/world/gen/area/IAreaFactory;
accessible	method	net/minecraft/world/GameRules	register	(Ljava/lang/String;Lnet/minecraft/world/GameRules$Category;Lnet/minecraft/world/GameRules$RuleType;)Lnet/minecraft/world/GameRules$RuleKey;
accessible	method	net/minecraft/block/NetherRootsBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/GrindstoneBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/loot/LootPool	bonusRolls	Lnet/minecraft/loot/RandomValueRange;
mutable	field	net/minecraft/loot/LootPool	bonusRolls	Lnet/minecraft/loot/RandomValueRange;
accessible	field	net/minecraft/loot/LootPool	rolls	Lnet/minecraft/loot/IRandomRange;
mutable	field	net/minecraft/loot/LootPool	rolls	Lnet/minecraft/loot/IRandomRange;
accessible	method	net/minecraft/block/DoorBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/tags/BlockTags	makeWrapperTag	(Ljava/lang/String;)Lnet/minecraft/tags/ITag$INamedTag;
accessible	field	net/minecraft/client/gui/overlay/DebugOverlayGui	rayTraceFluid	Lnet/minecraft/util/math/RayTraceResult;
accessible	field	net/minecraft/client/gui/overlay/DebugOverlayGui	rayTraceBlock	Lnet/minecraft/util/math/RayTraceResult;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	identityMap	Ljava/util/IdentityHashMap;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	objectList	Ljava/util/List;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	nextId	I
accessible	method	net/minecraft/block/BreakableBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/client/gui/ScreenManager	registerFactory	(Lnet/minecraft/inventory/container/ContainerType;Lnet/minecraft/client/gui/ScreenManager$IScreenFactory;)V
accessible	field	net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer	blockRenderer	Lnet/minecraft/client/renderer/BlockRendererDispatcher;
mutable	field	net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer	blockRenderer	Lnet/minecraft/client/renderer/BlockRendererDispatcher;
accessible	method	net/minecraft/block/HorizontalFaceBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/server/MinecraftServer	serverTime	J
accessible	method	net/minecraft/entity/monster/StrayEntity	getStepSound	()Lnet/minecraft/util/SoundEvent;
accessible	method	net/minecraft/block/SpongeBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/resources/FallbackResourceManager	resourcePacks	Ljava/util/List;
accessible	method	net/minecraft/command/arguments/EntityOptions	register	(Ljava/lang/String;Lnet/minecraft/command/arguments/EntityOptions$IFilter;Ljava/util/function/Predicate;Lnet/minecraft/util/text/ITextComponent;)V
accessible	method	net/minecraft/block/KelpTopBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/tileentity/HopperTileEntity	mayTransfer	()Z
accessible	method	net/minecraft/tileentity/HopperTileEntity	setTransferCooldown	(I)V
accessible	method	net/minecraft/block/FarmlandBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/PressurePlateBlock	<init>	(Lnet/minecraft/block/PressurePlateBlock$Sensitivity;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/client/renderer/tileentity/TileEntityRendererDispatcher	fontRenderer	Lnet/minecraft/client/gui/FontRenderer;
accessible	method	net/minecraft/client/renderer/entity/LivingRenderer	addLayer	(Lnet/minecraft/client/renderer/entity/layers/LayerRenderer;)Z
accessible	method	net/minecraft/entity/EntitySpawnPlacementRegistry	register	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/entity/EntitySpawnPlacementRegistry$PlacementType;Lnet/minecraft/world/gen/Heightmap$Type;Lnet/minecraft/entity/EntitySpawnPlacementRegistry$IPlacementPredicate;)V
accessible	method	net/minecraft/block/CarvedPumpkinBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/LilyPadBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/DispenserBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/SixWayBlock	<init>	(FLnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/FireBlock	getFlammability	(Lnet/minecraft/block/BlockState;)I
accessible	method	net/minecraft/block/FireBlock	getFireSpreadSpeed	(Lnet/minecraft/block/BlockState;)I
accessible	method	net/minecraft/block/LadderBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/client/renderer/model/ItemOverrideList	<init>	()V
accessible	method	net/minecraft/entity/monster/SkeletonEntity	getStepSound	()Lnet/minecraft/util/SoundEvent;
accessible	field	net/minecraft/world/gen/DebugChunkGenerator	GRID_WIDTH	I
mutable	field	net/minecraft/world/gen/DebugChunkGenerator	GRID_WIDTH	I
accessible	field	net/minecraft/world/gen/DebugChunkGenerator	GRID_HEIGHT	I
mutable	field	net/minecraft/world/gen/DebugChunkGenerator	GRID_HEIGHT	I
accessible	field	net/minecraft/world/gen/DebugChunkGenerator	ALL_VALID_STATES	Ljava/util/List;
mutable	field	net/minecraft/world/gen/DebugChunkGenerator	ALL_VALID_STATES	Ljava/util/List;
accessible	method	net/minecraft/entity/monster/AbstractSkeletonEntity	getStepSound	()Lnet/minecraft/util/SoundEvent;
accessible	method	net/minecraft/block/PaneBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/entity/player/PlayerEntity	closeScreen	()V
accessible	method	net/minecraft/block/CoralWallFanBlock	<init>	(Lnet/minecraft/block/Block;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/entity/item/TNTEntity	explode	()V
accessible	field	net/minecraft/world/biome/BiomeGenerationSettings$Builder	features	Ljava/util/List;
accessible	field	net/minecraft/world/biome/BiomeGenerationSettings$Builder	structures	Ljava/util/List;
accessible	field	net/minecraft/world/biome/BiomeGenerationSettings$Builder	surfaceBuilder	Ljava/util/Optional;
accessible	field	net/minecraft/world/biome/BiomeGenerationSettings$Builder	carvers	Ljava/util/Map;
accessible	method	net/minecraft/world/biome/BiomeGenerationSettings$Builder	populateStageEntries	(I)V
accessible	method	net/minecraft/block/RailBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	class	net/minecraft/inventory/container/ContainerType$IFactory
accessible	method	net/minecraft/block/StoneButtonBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/LoomBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/world/server/ServerChunkProvider	generator	Lnet/minecraft/world/gen/ChunkGenerator;
accessible	field	net/minecraft/world/server/ServerChunkProvider	world	Lnet/minecraft/world/server/ServerWorld;
accessible	method	net/minecraft/block/BarrierBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/world/raid/Raid$WaveMember	VALUES	[Lnet/minecraft/world/raid/Raid$WaveMember;
mutable	field	net/minecraft/world/raid/Raid$WaveMember	VALUES	[Lnet/minecraft/world/raid/Raid$WaveMember;
accessible	method	net/minecraft/client/renderer/entity/ItemRenderer	getModelCount	(Lnet/minecraft/item/ItemStack;)I
accessible	method	net/minecraft/block/ChorusFlowerBlock	<init>	(Lnet/minecraft/block/ChorusPlantBlock;Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/world/gen/blockplacer/BlockPlacerType	<init>	(Lcom/mojang/serialization/Codec;)V
accessible	method	net/minecraft/block/CropsBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/WitherSkeletonSkullBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	method	net/minecraft/block/FungusBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;Ljava/util/function/Supplier;)V
accessible	method	net/minecraft/item/PickaxeItem	<init>	(Lnet/minecraft/item/IItemTier;IFLnet/minecraft/item/Item$Properties;)V
accessible	method	net/minecraft/block/JigsawBlock	<init>	(Lnet/minecraft/block/AbstractBlock$Properties;)V
accessible	field	net/minecraft/entity/player/ServerPlayerEntity	currentWindowId	I
accessible	method	net/minecraft/entity/player/ServerPlayerEntity	getNextWindowId	()V
