accessWidener	v1	named
accessible	method	net/minecraft/entity/merchant/villager/VillagerProfession	<init>	(Ljava/lang/String;Lnet/minecraft/village/PointOfInterestType;Lcom/google/common/collect/ImmutableSet;Lcom/google/common/collect/ImmutableSet;)V
accessible	method	net/minecraft/client/renderer/model/BlockPart	func_178236_a	(Lnet/minecraft/util/Direction;)[F
accessible	field	net/minecraft/world/server/ChunkHolder	field_219320_o	[S
mutable	field	net/minecraft/world/server/ChunkHolder	field_219320_o	[S
accessible	method	net/minecraft/advancements/CriteriaTriggers	func_192118_a	(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger;
accessible	field	net/minecraft/client/renderer/ItemModelMesher	field_199313_a	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
# All methods in net/minecraft/util/DamageSource are to be AccessTransform{access=PUBLIC}
accessible	method	net/minecraft/util/DamageSource	func_180136_u	()Z
accessible	method	net/minecraft/util/DamageSource	func_76353_a	(Lnet/minecraft/entity/projectile/AbstractArrowEntity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76352_a	()Z
accessible	method	net/minecraft/util/DamageSource	func_76358_a	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_94539_a	(Lnet/minecraft/world/Explosion;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76361_j	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_188405_b	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_92087_a	(Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_94541_c	()Z
accessible	method	net/minecraft/util/DamageSource	func_199683_a	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_151518_m	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_188404_v	()Lnet/minecraft/util/math/Vec3d;
accessible	method	net/minecraft/util/DamageSource	func_82726_p	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76362_a	(Lnet/minecraft/entity/projectile/DamagingProjectileEntity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76359_i	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76356_a	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76351_m	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_151519_b	(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/text/ITextComponent;
accessible	method	net/minecraft/util/DamageSource	func_76347_k	()Z
accessible	method	net/minecraft/util/DamageSource	func_76345_d	()F
accessible	method	net/minecraft/util/DamageSource	func_76350_n	()Z
accessible	method	net/minecraft/util/DamageSource	func_203096_a	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76348_h	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_188403_a	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76365_a	(Lnet/minecraft/entity/player/PlayerEntity;)Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76363_c	()Z
accessible	method	net/minecraft/util/DamageSource	func_151517_h	()Z
accessible	method	net/minecraft/util/DamageSource	func_76346_g	()Lnet/minecraft/entity/Entity;
accessible	method	net/minecraft/util/DamageSource	func_94540_d	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_76355_l	()Ljava/lang/String;
accessible	method	net/minecraft/util/DamageSource	func_76349_b	()Lnet/minecraft/util/DamageSource;
accessible	method	net/minecraft/util/DamageSource	func_82725_o	()Z
accessible	method	net/minecraft/util/DamageSource	func_76357_e	()Z
accessible	method	net/minecraft/util/DamageSource	func_76364_f	()Lnet/minecraft/entity/Entity;
accessible	method	net/minecraft/util/DamageSource	func_76354_b	(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;
# ------------------------------------------------
accessible	field	net/minecraft/client/gui/overlay/DebugOverlayGui	field_211538_h	Lnet/minecraft/util/math/RayTraceResult;
accessible	field	net/minecraft/client/gui/overlay/DebugOverlayGui	field_211537_g	Lnet/minecraft/util/math/RayTraceResult;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	field_148749_a	Ljava/util/IdentityHashMap;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	field_148748_b	Ljava/util/List;
accessible	field	net/minecraft/util/ObjectIntIdentityMap	field_195868_a	I
accessible	field	net/minecraft/item/Item	field_185051_m	Ljava/util/Map;
accessible	field	net/minecraft/inventory/container/RepairContainer	field_82856_l	I
accessible	method	net/minecraft/client/renderer/model/BlockPartFace$Deserializer	<init>	()V
accessible	field	net/minecraft/client/gui/widget/list/AbstractList$AbstractListEntry	list	Lnet/minecraft/client/gui/widget/list/AbstractList;
accessible	class	net/minecraft/item/crafting/Ingredient
extendable	class	net/minecraft/item/crafting/Ingredient
accessible	method	net/minecraft/item/crafting/Ingredient	func_199564_a	(Lnet/minecraft/network/PacketBuffer;)V
extendable	method	net/minecraft/item/crafting/Ingredient	func_199564_a	(Lnet/minecraft/network/PacketBuffer;)V
accessible	method	net/minecraft/item/crafting/Ingredient	<init>	(Ljava/util/stream/Stream;)V
accessible	method	net/minecraft/item/crafting/Ingredient	func_209357_a	(Ljava/util/stream/Stream;)Lnet/minecraft/item/crafting/Ingredient;
accessible	field	net/minecraft/world/storage/loot/LootPool	field_186456_d	Lnet/minecraft/world/storage/loot/RandomValueRange;
mutable	field	net/minecraft/world/storage/loot/LootPool	field_186456_d	Lnet/minecraft/world/storage/loot/RandomValueRange;
accessible	field	net/minecraft/world/storage/loot/LootPool	field_186455_c	Lnet/minecraft/world/storage/loot/IRandomRange;
mutable	field	net/minecraft/world/storage/loot/LootPool	field_186455_c	Lnet/minecraft/world/storage/loot/IRandomRange;
accessible	method	net/minecraft/client/gui/ScreenManager	func_216911_a	(Lnet/minecraft/inventory/container/ContainerType;Lnet/minecraft/client/gui/ScreenManager$IScreenFactory;)V
accessible	field	net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer	field_178462_c	Lnet/minecraft/client/renderer/BlockRendererDispatcher;
mutable	field	net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer	field_178462_c	Lnet/minecraft/client/renderer/BlockRendererDispatcher;
accessible	method	net/minecraft/client/particle/ParticleManager	func_215234_a	(Lnet/minecraft/particles/ParticleType;Lnet/minecraft/client/particle/ParticleManager$IParticleMetaFactory;)V
accessible	method	net/minecraft/client/particle/ParticleManager	func_199283_a	(Lnet/minecraft/particles/ParticleType;Lnet/minecraft/client/particle/IParticleFactory;)V
accessible	field	net/minecraft/server/MinecraftServer	field_211151_aa	J
accessible	method	net/minecraft/entity/monster/StrayEntity	func_190727_o	()Lnet/minecraft/util/SoundEvent;
accessible	method	net/minecraft/entity/Entity	func_70022_Q	()Ljava/lang/String;
accessible	class	net/minecraft/item/crafting/Ingredient$IItemList
accessible	field	net/minecraft/resources/FallbackResourceManager	field_199023_a	Ljava/util/List;
accessible	method	net/minecraft/entity/ai/brain/schedule/Activity	<init>	(Ljava/lang/String;)V
accessible	field	net/minecraft/data/RecipeProvider	field_200413_c	Lnet/minecraft/data/DataGenerator;
accessible	method	net/minecraft/data/RecipeProvider	func_200409_a	(Lnet/minecraft/tags/Tag;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	func_208310_b	(Lnet/minecraft/data/DirectoryCache;Lcom/google/gson/JsonObject;Ljava/nio/file/Path;)V
accessible	method	net/minecraft/data/RecipeProvider	func_200408_a	(Lnet/minecraft/advancements/criterion/MinMaxBounds$IntBound;Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	func_200404_a	(Ljava/util/function/Consumer;)V
accessible	method	net/minecraft/data/RecipeProvider	func_200403_a	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	func_200407_a	(Lnet/minecraft/block/Block;)Lnet/minecraft/advancements/criterion/EnterBlockTrigger$Instance;
accessible	method	net/minecraft/data/RecipeProvider	func_200405_a	([Lnet/minecraft/advancements/criterion/ItemPredicate;)Lnet/minecraft/advancements/criterion/InventoryChangeTrigger$Instance;
accessible	method	net/minecraft/command/arguments/EntityOptions	func_202024_a	(Ljava/lang/String;Lnet/minecraft/command/arguments/EntityOptions$IFilter;Ljava/util/function/Predicate;Lnet/minecraft/util/text/ITextComponent;)V
accessible	field	net/minecraft/util/WeightedRandom$Item	field_76292_a	I
accessible	class	net/minecraft/tags/BlockTags$Wrapper
accessible	method	net/minecraft/command/arguments/EntitySelectorParser	func_197396_n	()V
accessible	method	net/minecraft/command/arguments/EntitySelectorParser	func_197404_d	()V
accessible	method	net/minecraft/item/AxeItem	<init>	(Lnet/minecraft/item/IItemTier;FFLnet/minecraft/item/Item$Properties;)V
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177602_b	Ljava/util/Set;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177609_j	Lnet/minecraft/client/renderer/texture/AtlasTexture;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_217853_J	Lnet/minecraft/client/renderer/texture/AtlasTexture$SheetData;
mutable	field	net/minecraft/client/renderer/model/ModelBakery	field_217853_J	Lnet/minecraft/client/renderer/texture/AtlasTexture$SheetData;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177598_f	Lnet/minecraft/resources/IResourceManager;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177606_o	Lnet/minecraft/client/renderer/model/BlockModel;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177604_a	Lnet/minecraft/client/renderer/model/ModelResourceLocation;
accessible	field	net/minecraft/client/renderer/model/ModelBakery	field_177616_r	Lnet/minecraft/client/renderer/model/BlockModel;
accessible	method	net/minecraft/client/renderer/model/ModelBakery	func_177594_c	(Lnet/minecraft/util/ResourceLocation;)Lnet/minecraft/client/renderer/model/BlockModel;
accessible	method	net/minecraft/tileentity/HopperTileEntity	func_174914_o	()Z
accessible	method	net/minecraft/tileentity/HopperTileEntity	func_145896_c	(I)V
accessible	field	net/minecraft/client/renderer/model/BlockModel	field_178315_d	Lnet/minecraft/client/renderer/model/BlockModel;
accessible	field	net/minecraft/client/renderer/model/BlockModel	field_178322_i	Z
accessible	field	net/minecraft/client/renderer/model/BlockModel	field_178318_c	Ljava/util/Map;
accessible	method	net/minecraft/client/renderer/model/BlockModel	func_187966_f	()Ljava/util/List;
accessible	method	net/minecraft/village/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;ILnet/minecraft/util/SoundEvent;Ljava/util/function/Predicate;I)V
accessible	method	net/minecraft/village/PointOfInterestType	<init>	(Ljava/lang/String;Ljava/util/Set;ILnet/minecraft/util/SoundEvent;I)V
accessible	field	net/minecraft/client/audio/SoundEngine	field_148622_c	Lnet/minecraft/client/audio/SoundHandler;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218475_b	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218476_a	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218463_a	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/world/storage/loot/IRandomRange;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218570_h	(Lnet/minecraft/block/Block;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218561_b	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218491_c	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218541_a	(Lnet/minecraft/block/Block;Lnet/minecraft/item/Item;Lnet/minecraft/item/Item;Lnet/minecraft/world/storage/loot/conditions/ILootCondition$IBuilder;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218562_a	(Lnet/minecraft/block/Block;Lnet/minecraft/state/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218523_c	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218515_b	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218546_a	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218552_a	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/world/storage/loot/ILootFunctionConsumer;)Ljava/lang/Object;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218481_e	(Lnet/minecraft/block/Block;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218486_d	(Lnet/minecraft/util/IItemProvider;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218544_f	(Lnet/minecraft/block/Block;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218513_d	(Lnet/minecraft/block/Block;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218519_a	(Lnet/minecraft/block/Block;Lnet/minecraft/world/storage/loot/LootEntry$Builder;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218522_a	(Lnet/minecraft/block/Block;Ljava/util/function/Function;)V
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218494_a	(Lnet/minecraft/block/Block;Lnet/minecraft/world/storage/loot/conditions/ILootCondition$IBuilder;Lnet/minecraft/world/storage/loot/LootEntry$Builder;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218559_g	(Lnet/minecraft/block/Block;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218507_a	(Lnet/minecraft/block/Block;Lnet/minecraft/world/storage/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218560_a	(Lnet/minecraft/util/IItemProvider;Lnet/minecraft/world/storage/loot/ILootConditionConsumer;)Ljava/lang/Object;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218535_c	(Lnet/minecraft/block/Block;Lnet/minecraft/world/storage/loot/LootEntry$Builder;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218530_a	(Lnet/minecraft/block/Block;Lnet/minecraft/util/IItemProvider;Lnet/minecraft/world/storage/loot/IRandomRange;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218540_a	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218526_b	(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;[F)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	method	net/minecraft/data/loot/BlockLootTables	func_218511_b	(Lnet/minecraft/block/Block;Lnet/minecraft/world/storage/loot/LootEntry$Builder;)Lnet/minecraft/world/storage/loot/LootTable$Builder;
accessible	field	net/minecraft/client/renderer/tileentity/TileEntityRendererDispatcher	field_147557_n	Lnet/minecraft/client/gui/FontRenderer;
accessible	method	net/minecraft/client/renderer/model/BlockPart$Deserializer	<init>	()V
accessible	method	net/minecraft/client/renderer/entity/LivingRenderer	func_177094_a	(Lnet/minecraft/client/renderer/entity/layers/LayerRenderer;)Z
accessible	field	net/minecraft/client/Minecraft	field_71446_o	Lnet/minecraft/client/renderer/texture/TextureManager;
accessible	method	net/minecraft/client/Minecraft	func_193986_ar	()V
accessible	method	net/minecraft/client/Minecraft	func_184119_a	(Lnet/minecraft/item/ItemStack;Lnet/minecraft/tileentity/TileEntity;)Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/entity/MobEntity	field_70714_bg	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	field	net/minecraft/entity/MobEntity	field_70715_bh	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	method	net/minecraft/entity/EntitySpawnPlacementRegistry	func_209343_a	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/entity/EntitySpawnPlacementRegistry$PlacementType;Lnet/minecraft/world/gen/Heightmap$Type;Lnet/minecraft/entity/EntitySpawnPlacementRegistry$IPlacementPredicate;)V
accessible	method	net/minecraft/entity/ai/brain/memory/MemoryModuleType	<init>	(Ljava/util/Optional;)V
accessible	method	net/minecraft/inventory/container/ContainerType	<init>	(Lnet/minecraft/inventory/container/ContainerType$IFactory;)V
accessible	method	net/minecraft/client/renderer/GameRenderer	func_175069_a	(Lnet/minecraft/util/ResourceLocation;)V
# All fields in net/minecraft/client/gui/IngameGui are to be AccessTransform{access=PROTECTED}
accessible	field	net/minecraft/client/gui/IngameGui	field_175200_y	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/IngameGui	field_73843_a	F
accessible	field	net/minecraft/client/gui/IngameGui	field_175201_x	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/IngameGui	field_110329_b	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	field_184049_t	Lnet/minecraft/client/gui/overlay/SubtitleOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_175191_F	J
accessible	field	net/minecraft/client/gui/IngameGui	field_175199_z	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175192_A	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175189_D	I
accessible	field	net/minecraft/client/gui/IngameGui	field_73839_d	Lnet/minecraft/client/Minecraft;
accessible	field	net/minecraft/client/gui/IngameGui	field_73837_f	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175193_B	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175194_C	I
accessible	field	net/minecraft/client/gui/IngameGui	field_73838_g	Ljava/lang/String;
accessible	field	net/minecraft/client/gui/IngameGui	field_73845_h	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175190_E	J
accessible	field	net/minecraft/client/gui/IngameGui	field_73840_e	Lnet/minecraft/client/gui/NewChatGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_73842_c	Ljava/util/Random;
accessible	field	net/minecraft/client/gui/IngameGui	field_184050_w	Lnet/minecraft/client/gui/overlay/BossOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_92017_k	I
accessible	field	net/minecraft/client/gui/IngameGui	field_92016_l	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/client/gui/IngameGui	field_73841_b	Lnet/minecraft/client/renderer/ItemRenderer;
accessible	field	net/minecraft/client/gui/IngameGui	field_110328_d	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	field_110330_c	Lnet/minecraft/util/ResourceLocation;
accessible	field	net/minecraft/client/gui/IngameGui	field_73844_j	Z
accessible	field	net/minecraft/client/gui/IngameGui	field_175195_w	I
accessible	field	net/minecraft/client/gui/IngameGui	field_175196_v	Lnet/minecraft/client/gui/overlay/PlayerTabOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_175197_u	Lnet/minecraft/client/gui/SpectatorGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_175198_t	Lnet/minecraft/client/gui/overlay/DebugOverlayGui;
accessible	field	net/minecraft/client/gui/IngameGui	field_194812_I	I
accessible	field	net/minecraft/client/gui/IngameGui	field_191743_I	Ljava/util/Map;
accessible	field	net/minecraft/client/gui/IngameGui	field_194811_H	I
# ------------------------------------------------
accessible	method	net/minecraft/client/gui/IngameGui	func_194802_a	(Lnet/minecraft/scoreboard/ScoreObjective;)V
accessible	method	net/minecraft/client/gui/IngameGui	func_194805_e	(F)V
accessible	method	net/minecraft/client/gui/IngameGui	func_194798_c	()V
accessible	method	net/minecraft/client/gui/IngameGui	func_194808_p	()V
accessible	method	net/minecraft/client/gui/IngameGui	func_212303_b	(Lnet/minecraft/entity/Entity;)V
accessible	field	net/minecraft/world/WorldType	field_77139_a	[Lnet/minecraft/world/WorldType;
mutable	field	net/minecraft/world/WorldType	field_77139_a	[Lnet/minecraft/world/WorldType;
accessible	class	net/minecraft/item/crafting/Ingredient$SingleItemList
accessible	method	net/minecraft/item/crafting/Ingredient$SingleItemList	<init>	(Lnet/minecraft/item/ItemStack;)V
accessible	method	net/minecraft/block/Block$Properties	func_200951_a	(I)Lnet/minecraft/block/Block$Properties;
accessible	method	net/minecraft/block/Block$Properties	func_200943_b	(F)Lnet/minecraft/block/Block$Properties;
accessible	method	net/minecraft/block/Block$Properties	func_208770_d	()Lnet/minecraft/block/Block$Properties;
accessible	method	net/minecraft/block/Block$Properties	func_200944_c	()Lnet/minecraft/block/Block$Properties;
accessible	method	net/minecraft/block/Block$Properties	func_200947_a	(Lnet/minecraft/block/SoundType;)Lnet/minecraft/block/Block$Properties;
accessible	method	net/minecraft/block/Block$Properties	func_222380_e	()Lnet/minecraft/block/Block$Properties;
accessible	class	net/minecraft/item/crafting/TippedArrowRecipe
accessible	method	net/minecraft/client/renderer/BufferBuilder	func_178972_a	(IIII)V
accessible	method	net/minecraft/client/renderer/BufferBuilder	func_78909_a	(I)I
accessible	method	net/minecraft/world/chunk/ChunkStatus	<init>	(Ljava/lang/String;Lnet/minecraft/world/chunk/ChunkStatus;ILjava/util/EnumSet;Lnet/minecraft/world/chunk/ChunkStatus$Type;Lnet/minecraft/world/chunk/ChunkStatus$IGenerationWorker;Lnet/minecraft/world/chunk/ChunkStatus$ILoadingWorker;)V
accessible	method	net/minecraft/entity/monster/WitherSkeletonEntity	func_190727_o	()Lnet/minecraft/util/SoundEvent;
accessible	class	net/minecraft/client/particle/ParticleManager$IParticleMetaFactory
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	field_178360_b	Lnet/minecraft/client/renderer/Vector3f;
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	field_178362_a	Lnet/minecraft/client/renderer/Vector3f;
accessible	field	net/minecraft/client/renderer/model/ItemTransformVec3f$Deserializer	field_178361_c	Lnet/minecraft/client/renderer/Vector3f;
accessible	method	net/minecraft/world/biome/Biome	func_180626_a	(Lnet/minecraft/util/math/BlockPos;)F
accessible	field	net/minecraft/world/biome/provider/BiomeProvider	field_201540_a	Ljava/util/List;
accessible	class	net/minecraft/nbt/NumberNBT
accessible	field	net/minecraft/entity/item/ExperienceOrbEntity	field_70530_e	I
accessible	method	net/minecraft/block/Block	func_180637_b	(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;I)V
accessible	field	net/minecraft/data/loot/EntityLootTables	field_218586_a	Lnet/minecraft/advancements/criterion/EntityPredicate$Builder;
accessible	method	net/minecraft/data/loot/EntityLootTables	func_218585_a	(Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/world/storage/loot/LootTable$Builder;)V
accessible	method	net/minecraft/data/loot/EntityLootTables	func_218582_a	(Lnet/minecraft/entity/EntityType;Lnet/minecraft/world/storage/loot/LootTable$Builder;)V
accessible	method	net/minecraft/client/renderer/model/ItemOverrideList	<init>	()V
accessible	method	net/minecraft/client/renderer/model/ItemCameraTransforms$Deserializer	<init>	()V
accessible	method	net/minecraft/world/biome/DeepFrozenOceanBiome	func_180626_a	(Lnet/minecraft/util/math/BlockPos;)F
accessible	class	net/minecraft/item/crafting/Ingredient$TagList
accessible	method	net/minecraft/item/crafting/Ingredient$TagList	<init>	(Lnet/minecraft/tags/Tag;)V
accessible	field	net/minecraft/client/renderer/entity/EntityRendererManager	field_78729_o	Ljava/util/Map;
accessible	method	net/minecraft/client/renderer/entity/EntityRendererManager	func_217782_a	(Ljava/lang/Class;Lnet/minecraft/client/renderer/entity/EntityRenderer;)V
accessible	method	net/minecraft/entity/monster/SkeletonEntity	func_190727_o	()Lnet/minecraft/util/SoundEvent;
accessible	field	net/minecraft/world/Teleporter	field_85191_c	Ljava/util/Map;
accessible	field	net/minecraft/world/Teleporter	field_85192_a	Lnet/minecraft/world/server/ServerWorld;
accessible	field	net/minecraft/world/Teleporter	field_77187_a	Ljava/util/Random;
accessible	method	net/minecraft/entity/monster/AbstractSkeletonEntity	func_190727_o	()Lnet/minecraft/util/SoundEvent;
accessible	class	net/minecraft/world/gen/IChunkGeneratorFactory
accessible	field	net/minecraft/server/dedicated/DedicatedServer	field_71341_l	Ljava/util/List;
accessible	field	net/minecraft/entity/player/PlayerEntity	field_71077_c	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/entity/player/PlayerEntity	field_82248_d	Z
accessible	method	net/minecraft/entity/player/PlayerEntity	func_71053_j	()V
accessible	method	net/minecraft/particles/ParticleType	<init>	(ZLnet/minecraft/particles/IParticleData$IDeserializer;)V
accessible	method	net/minecraft/client/renderer/model/BlockFaceUV$Deserializer	<init>	()V
accessible	method	net/minecraft/entity/item/TNTEntity	func_70515_d	()V
accessible	class	net/minecraft/client/gui/ScreenManager$IScreenFactory
accessible	method	net/minecraft/world/biome/FrozenOceanBiome	func_180626_a	(Lnet/minecraft/util/math/BlockPos;)F
accessible	class	net/minecraft/inventory/container/ContainerType$IFactory
accessible	method	net/minecraft/client/renderer/ItemRenderer	func_191970_a	(Lnet/minecraft/client/renderer/BufferBuilder;Ljava/util/List;ILnet/minecraft/item/ItemStack;)V
accessible	method	net/minecraft/fluid/Fluid	func_180664_k	()Lnet/minecraft/util/BlockRenderLayer;
accessible	class	net/minecraft/data/ShapedRecipeBuilder$Result
accessible	field	net/minecraft/world/server/ServerChunkProvider	field_186029_c	Lnet/minecraft/world/gen/ChunkGenerator;
accessible	field	net/minecraft/world/server/ServerChunkProvider	field_73251_h	Lnet/minecraft/world/server/ServerWorld;
accessible	field	net/minecraft/item/ItemGroup	field_78032_a	[Lnet/minecraft/item/ItemGroup;
mutable	field	net/minecraft/item/ItemGroup	field_78032_a	[Lnet/minecraft/item/ItemGroup;
accessible	field	net/minecraft/world/World	field_73004_o	F
accessible	field	net/minecraft/world/World	field_73003_n	F
accessible	field	net/minecraft/world/World	field_73018_p	F
accessible	field	net/minecraft/world/World	field_73017_q	F
accessible	method	net/minecraft/world/World	func_175701_a	(Lnet/minecraft/util/math/BlockPos;)Z
accessible	method	net/minecraft/world/World	func_189509_E	(Lnet/minecraft/util/math/BlockPos;)Z
accessible	field	net/minecraft/resources/ResourcePack	field_195771_a	Ljava/io/File;
accessible	method	net/minecraft/client/renderer/entity/ItemRenderer	func_177078_a	(Lnet/minecraft/item/ItemStack;)I
accessible	method	net/minecraft/client/renderer/texture/TextureAtlasSprite	func_195665_a	(IIII)I
accessible	method	net/minecraft/particles/BasicParticleType	<init>	(Z)V
accessible	method	net/minecraft/item/PickaxeItem	<init>	(Lnet/minecraft/item/IItemTier;IFLnet/minecraft/item/Item$Properties;)V
accessible	field	net/minecraft/network/status/server/SServerInfoPacket	field_149297_a	Lcom/google/gson/Gson;
accessible	method	net/minecraft/util/concurrent/ThreadTaskExecutor	func_213165_a	(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;
accessible	field	net/minecraft/entity/player/ServerPlayerEntity	field_71139_cq	I
accessible	method	net/minecraft/entity/player/ServerPlayerEntity	func_71117_bO	()V
accessible	method	net/minecraft/world/gen/layer/LayerUtil	func_202829_a	(JLnet/minecraft/world/gen/layer/traits/IAreaTransformer1;Lnet/minecraft/world/gen/area/IAreaFactory;ILjava/util/function/LongFunction;)Lnet/minecraft/world/gen/area/IAreaFactory;
accessible	method	net/minecraft/world/GameRules	func_223595_a	(Ljava/lang/String;Lnet/minecraft/world/GameRules$RuleType;)Lnet/minecraft/world/GameRules$RuleKey;
accessible	method	net/minecraft/client/renderer/model/ItemOverride$Deserializer	<init>	()V
accessible	method	net/minecraft/entity/ai/brain/sensor/SensorType	<init>	(Ljava/util/function/Supplier;)V
